---
projectName: "kolotoc"
image:
  repository: "nmatare/kolotoc"
  tag: "latest"
  pullPolicy: IfNotPresent

cuda:
  stubs: "/usr/local/cuda/targets/x86_64-linux/lib/stubs"

ssh:
  port: 3222
  hostKey: |-
    #  -----BEGIN RSA PRIVATE KEY-----
    #  YourPrivateKey
    #  -----END RSA PRIVATE KEY-----
  hostKeyPub: |-
    #  ssh-rsa YourPublicKey

scheduler:
  schedulerPort: 8686
  dashboardPort: 8687
  jupyterPort: 8889
  tensorboardPort: 5056
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 5Gi

ring:
  number: 1
  workers: 1  # one dask-worker process per pod
  gpus: 0
