---
projectName: "kolotoc"
image:
  repository: "nmatare/kolotoc"
  tag: "latest"
  pullPolicy: IfNotPresent

cuda:
  stubs: "/usr/local/cuda/targets/x86_64-linux/lib/stubs"

ssh:
  port: 3222
  hostKey: |-
    #  -----BEGIN RSA PRIVATE KEY-----
    #  YourPrivateKey
    #  -----END RSA PRIVATE KEY-----
  hostKeyPub: |-
    #  ssh-rsa YourPublicKey

scheduler:
  schedulerPort: 8686
  dashboardPort: 8687
  jupyterPort: 8889
  tensorboardPort: 5056
  resources:
    requests:
      cpu: "1"
      memory: 5G
    limits:
      cpu: "1"
      memory: 5G

carrier:
  number: 1
  resources: 
    requests:
      cpu: 1
      memory: 6G
    limits:
      cpu: 1
      memory: 6G

tower:
  number: 1
  resources:
    requests:
      cpu: 1
      memory: 6G
      nvidia.com/gpu: 0
    limits:
      cpu: 1
      memory: 6G
      nvidia.com/gpu: 0
