
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "kolotoc.fullname" . }}-carrier
  labels:
    app: {{ template "kolotoc.name" . }}
    chart: {{ template "kolotoc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: carrier
spec:
  replicas: {{ .Values.carrier.number }}
  selector:
    matchLabels:
      app: {{ template "kolotoc.name" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: carrier
  serviceName: {{ template "kolotoc.fullname" . }}-carrier
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "kolotoc.name" . }}
        chart: {{ template "kolotoc.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: carrier
    spec:
      selector:
        matchLabels:
          app: {{ template "kolotoc.name" . }}
          release: {{ .Release.Name }}
          role: carrier
      hostNetwork: True
      hostPID: False
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: {{ template "kolotoc.fullname" . }}-config
        configMap:
          name: {{ template "kolotoc.fullname" . }}
          items:
          - key: scheduler.config
            path: scheduler.hostfile
            mode: 438
          - key: carrier.config
            path: carrier.hostfile
            mode: 438
          - key: ssh.readiness
            path: check.sh
            mode: 365
          - key: ssh.wait
            path: wait.sh
            mode: 365   
          - key: ssh.config
            path: ssh.sh
            mode: 365
          - key: cuda.config
            path: cuda.sh
            mode: 365
          - key: carrier.run
            path: run.sh
            mode: 365
      - name: {{ template "kolotoc.fullname" . }}-secret
        secret:
          secretName: {{ template "kolotoc.fullname" . }}
          defaultMode: 448
          items:
          - key: host-key
            path: id_rsa
          - key: host-key-pub
            path: authorized_keys
      containers:
      - name: kolotoc-carrier
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
        - name: PROJECT_NAME
          value: "{{ .Values.projectName }}"
        - name: OPENMPI_SSH_PORT
          value: "{{ .Values.ssh.port }}"
        - name: CUDA_STUB_LOCATION
          value: "{{ .Values.cuda.stubs }}"           
        - name: CARRIER_MACHINE_CPU
          value: "{{ .Values.carrier.resources.requests.cpu }}"
        - name: CARRIER_MACHINE_MEMORY
          value: "{{ .Values.carrier.resources.requests.memory }}"
        - name: DASK_SCHEDULER_ADDRESS
          value: {{ template "kolotoc.fullname" . }}-scheduler
        - name: DASK_SCHEDULER_PORT
          value: "{{ .Values.scheduler.schedulerPort }}"
     {{- if .Values.env }}
     {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
     {{- end }}
     {{- end }}
        securityContext:
          privileged: true
        ports:
        - containerPort: {{ .Values.ssh.port }}
        volumeMounts:
        - name: {{ template "kolotoc.fullname" . }}-config
          mountPath: /kolotoc/generated
        - name: {{ template "kolotoc.fullname" . }}-secret
          readOnly: true
          mountPath: "/etc/secret-volume"          
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 8 }}
{{- end }}
        command: ["/bin/bash", "-c"]
        args: [". /kolotoc/generated/ssh.sh && 
                . /kolotoc/generated/cuda.sh && 
                . /kolotoc/generated/wait.sh && 
                . /kolotoc/generated/run.sh"]
        readinessProbe:
          exec:
            command:
            - /kolotoc/generated/check.sh
          initialDelaySeconds: 1
          periodSeconds: 2
        resources:
          requests:
            cpu: "{{ .Values.carrier.resources.requests.cpu }}"
            memory: "{{ .Values.carrier.resources.requests.memory }}"
            nvidia.com/gpu: 0
          limits:
            cpu: "{{ .Values.carrier.resources.limits.cpu }}"
            memory: "{{ .Values.carrier.resources.limits.memory }}"
            nvidia.com/gpu: 0
      tolerations:
        - key: "node"
          operator: "Equal"
          value: "carrier"
          effect: "NoSchedule"