---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "kolotoc.fullname" . }}
  labels:
    app: {{ template "kolotoc.name" . }}
    chart: {{ template "kolotoc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Deployment }}
    role: scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "kolotoc.name" . }}
        release: {{ .Release.Name }}
        role: scheduler
    spec:
      {{- if .Values.useHostNetwork }}
      hostNetwork: {{ .Values.useHostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- if .Values.useHostPID }}
      hostPID: {{ .Values.useHostPID }}
      {{- end }}
      restartPolicy: Always
      volumes:
      - name: {{ template "kolotoc.fullname" . }}-config
        configMap:
          name: {{ template "kolotoc.fullname" . }}
          items:
          - key: hostfile.config
            path: hostfile
            mode: 438
          - key: scheduler.waitWorkerReady
            path: waitWorkersReady.sh
            mode: 365
          - key: scheduler.run
            path: run.sh
            mode: 365
      - name: {{ template "kolotoc.fullname" . }}-secret
        secret:
          secretName: {{ template "kolotoc.fullname" . }}
          defaultMode: 448
          items:
          - key: host-key
            path: id_rsa
          - key: host-key-pub
            path: authorized_keys
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent  6 }}
{{- end }}
      containers:
      - name: kolotoc-scheduler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
         - name: PROJECT_NAME
           value: "{{ .Values.projectName }}"
         - name: CUDA_STUB_LOCATION
           value: "{{ .Values.cuda.stubs }}"
         - name: DASK_SCHEDULER_PORT
           value: "{{ .Values.scheduler.schedulerPort }}"
         - name: BOKEH_PORT
           value: "{{ .Values.scheduler.bokehPort }}"
         - name: JUPYTER_LAB_PORT
           value: "{{ .Values.scheduler.jupyterPort }}"
         - name: TENSORBOARD_PORT
           value: "{{ .Values.scheduler.tensorboardPort }}"
         - name: HOST_SSH_PORT
           value: "{{ .Values.ssh.port }}"
       {{- if .Values.scheduler.env }}
       {{- range $key, $value := .Values.scheduler.env }}
         - name: "{{ $key }}"
           value: "{{ $value }}"
       {{- end }}
       {{- end }}
{{- if .Values.scheduler.privileged }}
        securityContext:
          privileged: true
{{- end }}
        ports:
        - containerPort: {{ .Values.ssh.port }}
        volumeMounts:
        - name: {{ template "kolotoc.fullname" . }}-config
          mountPath: /kolotoc/generated
        - name: {{ template "kolotoc.fullname" . }}-secret
          readOnly: true
          mountPath: "/etc/secret-volume"
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 8 }}
{{- end }}
        command:
        - /kolotoc/generated/run.sh
        args:
{{ toYaml .Values.scheduler.args | indent 10 }}
      initContainers:
      - name: wait-workers
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: HOST_SSH_PORT
          value: "{{ .Values.ssh.port }}"
        {{- if .Values.scheduler.env }}
        {{- range $key, $value := .Values.scheduler.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        command:
        - /kolotoc/generated/waitWorkersReady.sh
        args:
        - /kolotoc/generated/hostfile
        volumeMounts:
        - name: {{ template "kolotoc.fullname" . }}-config
          mountPath: /kolotoc/generated
        - name: {{ template "kolotoc.fullname" . }}-secret
          readOnly: true
          mountPath: "/etc/secret-volume"
      tolerations:
        - key: "node"
          operator: "Equal"
          value: "scheduler"
          effect: "NoSchedule"
