---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kolotoc.fullname" . }}-scheduler
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "kolotoc.chart" . }}
    app: {{ template "kolotoc.name" . }}
spec:
  clusterIP: None
  ports:
  - name: ssh 
    port: {{ .Values.ssh.port }}
    targetPort: {{ .Values.ssh.port }}
  selector:
    app: {{ template "kolotoc.name" . }}
    release: {{ .Release.Name }}
    role: scheduler
