---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kolotoc.fullname" . }}
  labels:
    app: {{ template "kolotoc.name" . }}
    chart: {{ template "kolotoc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  host-key: {{ .Values.ssh.hostKey | b64enc | quote }}
  host-key-pub: {{ .Values.ssh.hostKeyPub | b64enc | quote }}
